### ISSUE TITLE
Admin_RAW und Pass_RAW

### ISSUE THREAD

**Issue by christianTF** [marcelzoller/loxberry-plugin-vzug#1]
Hallo Marcel!

Sehr strukturierter Code!

Bezüglich loxberry-plugin-vzug/webfrontend/html/index.cgi

Du solltest nicht die RAW-Varianten der Felder nehmen, sondern die ohne RAW. 
Bzw. ich weiß nicht, wie LWP::Simple mit Credentials umgeht, jedenfalls sind Sonderzeichen in RAW nicht encoded, dh. es könnte sein, dass Umlaute nicht funktionieren mit den RAW-Variablen.

Lg, Christian

**Comment by marcelzoller** [comment]
Sali Christian

Da ich erst kürzlich Loyberry coden gestartet bin, sind Tips super. 

Jedoch verstehe ich noch nicht ganz, was du meinst? Von welchen RAW-Variablen sprichst du genau?

cheers, Marcel

**Comment by christianTF** [comment]
https://github.com/marcelzoller/loxberry-plugin-vzug/blob/d6cd3ea3c625e857b0d9911363cebb8d9793abaa/webfrontend/html/index.cgi#L24

https://www.loxwiki.eu/display/LOXBERRY/LoxBerry%3A%3ASystem%3A%3Aget_miniservers

In RAW steht z.B. `schön` und im gleichen Feld ohne RAW steht `sch%C3%B6n`.

Wenn LWP::Simple nicht selbst die Sonderzeichen encodet, solltest du die Nicht-RAW-Variante nehmen, sonst funktionieren Sonderzeichen im User und Passwort nicht.

lg, Christian

**Comment by marcelzoller** [comment]
fix in v0.6
