### ISSUE TITLE
Erweiterung um Strom & Wasserverbrauch

### ISSUE THREAD

**Issue by samuelmueller** [marcelzoller/loxberry-plugin-vzug#2]
Hallo @marcelzoller 

Ich habe im Internet eine API gefunden um den Strom bzw. Wasserverbrauch abzufragen. Da ich bis jetzt noch nie etwas für den LoxBerry programmiert habe, wollte ich Fragen ob du Interesse hättest dies bei deinem PlugIn ebenfalls einzubinden?

Über http://<IP>/hh?command=getEcoInfo kann ich bei meinen Adora V2000 (Waschmaschine & Tumbler) die Werte als JSON abfragen
{"water":{"total":30743.9,"average":47.5,"program":34.1,"option":0},"energy":{"total":369.5,"average":0.5,"program":0.3}}

Ich kann auch versuchen, dies in deinem PlugIn umzusetzen und einen PR zu machen, aber bis man in fremden Code drin ist, könnte es dauern

**Comment by marcelzoller** [comment]
Sali Samuel.
Vielen Dank für den API-Aufruf. Ich habe heute die PreVersion v2023.09.11 erstellt, wo Wasser und Stromverbrauch ausgelesen werden kann.


Hier die neuen Werte, die ausgelesen werden können:
WasserTotal1@45165
WasserAverage1@12
WasserProgram1@1
EnergyTotal1@3863
EnergyAverage1@0.9
EnergyProgram1@0.8
